### ISSUE TITLE
goto-last-change.el functionality is broken

### ISSUE THREAD

**Issue by anildigital** [anildigital/mix-format.el#8]
https://github.com/camdez/goto-last-change.el this package allows us to go to a cursor point where the last edit was made. I have bound `C-.` to ```(goto-last-change ARG)``` but with our current mix-format, pressing `C-.` always goes to the end of the file.

**Comment by ckruse** [comment]
Yeah, and it breaks undo as well. This is because we erase the buffer and insert the formatted output; to avoid that we would have to apply the changes as a patch. I already have some ideas how to solve that (that basically involves calling `diff` on the original and the formatted output and apply that), but I didn't have the time to implement this, yet. I hope I can make some spare time this evening; if not I will implement this approach tomorrow.

**Comment by ckruse** [comment]
I pushed a new branch with the modified behavior. I stole some code from go-mode (I wasn't sure how to handle patches), it works pretty well for me. Can you test if it works for you as well?

**Comment by anildigital** [comment]
@ckruse thanks.. will test it tonight!

**Comment by anildigital** [comment]
@ckruse works fabulously for me. I think we can merge it in. Could you send PR?

**Comment by ckruse** [comment]
Cool. Done :-)
